### ISSUE TITLE
Relaxed Discussion: Text and Description for feeds

### ISSUE THREAD

**Issue by little-endian-0x01** [abijithanikkuruthi/educollab#51]
- [ ] Determine if the operation is create or update (or anything else)
- [ ] Are the below changes applied?

We need to discuss on title and description for the feeds for following types:

1. **Curriculum Created:**
    - **Title -** Add final choice here 
    - **Description -** Add final choice here 

2. **Curriculum Updated:**
    - **Title -** Add final choice here 
    - **Description -** Add final choice here 
3. **Curriculum Subscribed:**
    - **Title -** Add final choice here 
    - **Description -** Add final choice here 
4. **Curriculum Unsubscribed:**
    - **Title -** Add final choice here 
    - **Description -** Add final choice here 
5. **Curriculum Teach:**
    - **Title -** Add final choice here 
    - **Description -** Add final choice here 
6. **Curriculum UnTeach:**
    - **Title -** Add final choice here 
    - **Description -** Add final choice here 
7. **Subject Subscribed:**
    - **Title -** Add final choice here 
    - **Description -** Add final choice here 
8. **Subject Unsubscribed:**
    - **Title -** Add final choice here 
    - **Description -** Add final choice here 
9. **Bit Created:**
    - **Title -** Add final choice here 
    - **Description -** Add final choice here 
10. **Bit Updated:**
    - **Title -** Add final choice here 
    - **Description -** Add final choice here 

Please add if I missed any.

**Comment by little-endian-0x01** [comment]
My suggestions:

Sub title will be just gray text with very small font just below or above the title. Ofcourse everything is linked to their respective pages.

1. **Curriculum Created:**
    - **Title -** New Curriculum - {curriculum name} created by {user name}
    - **Sub-Title:** {subject name}
    - **Description -** {User name} has created a new curriculum - {curriculum name} for {subject name} subject. Check it out!


2. **Curriculum Updated:**
    - **Title -** {curriculum name} updated by {user name}
    - **Sub-Title:** {subject name}
    - **Description -**  {User name} has updated the curriculum - {curriculum name} for {subject name} subject. See the changes!


3. **Curriculum Subscribed:**
    - **Title -** {User name} subscribed to Curriculum - {curriculum name} 
    - **Sub-Title:** {subject name}
    - **Description -** {User name} from {University name} has subscribed to the curriculum - {curriculum name} for {subject name} subject. Hooray!


4. **Curriculum Unsubscribed:**
    - **Title -** {User name} unsubscribed from Curriculum - {curriculum name} 
    - **Sub-Title:** {subject name}
    - **Description -** {User name} from {University name} has unsubscribed from the curriculum - {curriculum name} for {subject name} subject. Sad to see you go :(


5. **Curriculum Teach:**
    - **Title -** {University name for the user} has decided to teach curriculum - {curriculum name} at their institution.
    - **Sub-Title:** {subject name}
    - **Description -** {University name for the user} has decided to teach curriculum - {curriculum name} for  {subject name} subject  at their institution. One more addition to the club!


6. **Curriculum UnTeach:**
    - **Title -** {University name for the user} has decided to drop the curriculum - {curriculum name} at their institution.
    - **Sub-Title:** {subject name}
    - **Description -** {University name for the user} has decided to drop the curriculum - {curriculum name} for  {subject name} subject  at their institution. Check out which curriculum they are teaching now!


7. **Subject Subscribed:**
    - **Title -** {User name} subscribed to Subject - {subject name} 
    - **Sub-Title:** {Topic name}
    - **Description -** {User name} from {University name} has subscribed to the subject - {curriculum name} for {Topic name} course. Hooray!


8. **Subject Unsubscribed:**
    - **Title -** {User name} unsubscribed from Subject - {subject name} 
    - **Sub-Title:** {Topic name}
    - **Description -** {User name} from {University name} has unsubscribed from the subject - {curriculum name} for {Topic name} course. Sad to see you go :(


9. **Bit Created:**
    - **Title -** New Bit - {bit name} created in Curriculum - {curriculum name}.
    - **Sub-Title:** {subject name} >> {curriculum name}
    - **Description -** {User name} has created a new bit - {bit name} for the curriculum - {curriculum name} in {subject name} subject. Check it out!


10. **Bit Updated:**
    - **Title -** Bit - {bit name} in Curriculum - {curriculum name} is updated.
    - **Sub-Title:** {subject name} >> {curriculum name} 
    - **Description -** {User name} has updated the bit - {bit name} for the curriculum - {curriculum name} in {subject name} subject. See the changes!

**Comment by little-endian-0x01** [comment]
@l8518 @sophie-vos @abijithanikkuruthi  Check these out please :)

**Comment by abijithanikkuruthi** [comment]
My 2 cents:

We should only show feeds of Curriculum creation/updation and bit creation/updation/deletion.

Otherwise, it just adds a lot of noise to the feeds.

I would prefer if the "Teachers" and the "Subscribers" are listed in the curriculum view alone.
If I was a user, it doesn't really affect me if a prof decides to subscribe to a curriculum since the app is curriculum-centric and not user-centric.

PS: This isn't a strong opinion. Just my thoughts. I am okay with whatever is the popular opinion.

**Comment by little-endian-0x01** [comment]
Hmm. Makes sense to me. Could you make an issue?
