### ISSUE TITLE
Display File Uploads in Bit Show and Bit Edit

### ISSUE THREAD

**Issue by l8518** [abijithanikkuruthi/educollab#70]
Currently we do not display files on the curriculm page etc. - might need to fix that @abijithanikkuruthi  - Currently do not have an idea what is the best way to link files etc.

**Back-end:**
- [ ] Show uploaded file on bit show
- [ ] Show uploaded file on bit edit

**Front-end dependency on Back-end:**
- [ ] Prettify uploaded files with icon or whatever

**Comment by abijithanikkuruthi** [comment]
@l8518 
The url to the file can be obtained by {{bit.file.url}}
Options to consider -
1. Download button
2. Iframe in case it is a PDF/image
3. webframework (?)

My prefernce would be the easiest way which is a download button with <a href="{{bit.file.url}}" download="{{bit.file}}">

**Comment by abijithanikkuruthi** [comment]
<a href="{{bit.fil.url}}" download="{{bit.file}}">
